### PR TITLE
Removing gitlab file because it is no longer necessary

### PR DESCRIPTION
**Pull request by MichielDean**
Fix for issue #4

### CODE REVIEW

**Comment by MichielDean** [comment]
@khalludi I do not know why this build has failed. I have never done anything with Gradle or sonarqube.

The error is:

```
Task :sonarqube FAILED
SonarQube server [http://localhost:9000] can not be reached
```

Don't see how deleting this file could cause the build to fail.

https://travis-ci.com/khalludi/bookshare-backend/builds/97328708

**Comment by khalludi** [comment]
Hmm ... seems to be an issue on Travis-CI. It should be using a different server URL for Sonarqube. I'll see if I can't fix that real quick.

**Comment by khalludi** [comment]
@MichielDean I fixed the issue with Sonarqube not using the appropriate URL. If you can pull changes from master and resubmit the pull request, it should pass Travis-CI checks now. Thanks for contributing!

**Comment by MichielDean** [comment]
@khalludi Awesome, thanks. Still failed after I merged though.

**Comment by khalludi** [comment]
Hmm, that's really odd. Now it can't find the Sonarqube URL at all ...

**Comment by khalludi** [comment]
I finally figured out that the reason Travis-CI fails is because the secret env vars are not used if the request is made by anyone other than me. So basically, there's a little process I have to do to make this work.

**Pull request merged**
